---
# tasks file for justforfun
- name: apt update source list
  shell: apt update

- name: "Update cache & Full system update"
  apt:
    upgrade: dist
    update_cache: yes

- name: Install netplan network manager
  apt:
    name: netplan.io
    state: present

- name: Create a directory netplan if it does not exist
  file:
    path: /etc/netplan
    state: directory

- name: Configure netplan file
  template:
    src: netplan.j2
    dest: /etc/netplan/00-installer-config.yaml

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: Remove ifupdown package
  apt:
    name: ifupdown
    state: absent
